### ISSUE TITLE
Multiple material libraries maybe?

### ISSUE THREAD

**Issue by dt192** [Project-Cartographer/H2V-Blender-ASS-Exporter#10]
`Traceback (most recent call last):
  File "Blend2Halo2-Modified.py", line 534, in execute
    return write_asset(context, self.filepath, triangulate_faces=self.triangulate_faces, split_flat=self.split_flat)
  File "Blend2Halo2-Modified.py", line 322, in write_asset
    file.write('\n{0}'.format(materials_list.index(mesh.materials[poly.material_index].name)))
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1`

**Comment by General-101** [comment]
Upload the .blend file that causes this error

**Comment by dt192** [comment]
Seems to be when the material is parented to the object instead of the mesh.

[error.zip](https://github.com/Project-Cartographer/H2V-Blender-ASS-Exporter/files/4494156/error.zip)

Confirmed. It's when the material is linked to the 'Object' rather than the 'Data'.

**Comment by General-101** [comment]
Ye, I see it. I'll need to update the script to work more like the JMS script to prevent this error.
This will take a while. Until then just set the material to be linked to the mesh.

**Comment by dt192** [comment]
Work around for this for anybody else having issues. There is an addon included with Blender called material utilities. Install that, hit shift+Q and change the links to data. It's not great, as it doesn't unlink the material from the object, so you end up with double linked material unless you manually unlink it from the parent, but it does at least make the ass exporter work as expected.

![blenderissuesolution](https://user-images.githubusercontent.com/2612048/79635249-d3029d80-8167-11ea-80ae-ecf34509ef5f.jpg)
